import type {
  SpmNormedScaleCode,
  SpmNormEntry,
  SpmNormsTable,
} from "../_lib/spm/score";

type Cell = number | readonly [number, number] | null;

/** Uma linha do AutoScore: T + células raw por escala normativa. */
type NormRow = {
  tScore: number;
  percentile: number;
  SOC: Cell;
  VIS: Cell;
  HEA: Cell;
  TOU: Cell;
  BOD: Cell;
  BAL: Cell;
  PLA: Cell;
  TOT: Cell;
};

/**
 * Tabela AutoScore Casa 5–12 anos (SPM legado), digitalizada do formulário
 * de scores da clínica. Células vazias = null (raw não mapeia nesse T).
 *
 * Exemplo validado (Gustavo): raw 20,31,22,24,19,22,25,128 →
 * T 58,77,74,68,64,68,70,71 (SOC…TOT; sem coluna TAS).
 */
const ROWS: readonly NormRow[] = [
  {
    tScore: 80,
    percentile: 100,
    SOC: [37, 40],
    VIS: [35, 44],
    HEA: [29, 32],
    TOU: [37, 44],
    BOD: [36, 40],
    BAL: [35, 44],
    PLA: [33, 36],
    TOT: [170, 224],
  },
  {
    tScore: 79,
    percentile: 100,
    SOC: [35, 36],
    VIS: [33, 34],
    HEA: [27, 28],
    TOU: 36,
    BOD: [34, 35],
    BAL: 34,
    PLA: [31, 32],
    TOT: [164, 169],
  },
  {
    tScore: 78,
    percentile: 100,
    SOC: null,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: 33,
    PLA: null,
    TOT: [154, 163],
  },
  {
    tScore: 77,
    percentile: 99,
    SOC: 34,
    VIS: [31, 32],
    HEA: 26,
    TOU: [34, 35],
    BOD: 33,
    BAL: null,
    PLA: 30,
    TOT: [142, 153],
  },
  {
    tScore: 76,
    percentile: 99,
    SOC: null,
    VIS: null,
    HEA: 25,
    TOU: 33,
    BOD: 32,
    BAL: [31, 32],
    PLA: 29,
    TOT: [140, 141],
  },
  {
    tScore: 75,
    percentile: 99,
    SOC: 33,
    VIS: 30,
    HEA: 24,
    TOU: 32,
    BOD: 31,
    BAL: [29, 30],
    PLA: 28,
    TOT: [137, 139],
  },
  {
    tScore: 74,
    percentile: 99,
    SOC: null,
    VIS: [28, 29],
    HEA: [22, 23],
    TOU: [30, 31],
    BOD: 30,
    BAL: [27, 28],
    PLA: 27,
    TOT: [133, 136],
  },
  {
    tScore: 73,
    percentile: 99,
    SOC: 31,
    VIS: 27,
    HEA: null,
    TOU: [28, 29],
    BOD: 29,
    BAL: null,
    PLA: 26,
    TOT: [131, 132],
  },
  {
    tScore: 72,
    percentile: 99,
    SOC: null,
    VIS: 26,
    HEA: 21,
    TOU: null,
    BOD: 28,
    BAL: 26,
    PLA: null,
    TOT: [129, 130],
  },
  {
    tScore: 71,
    percentile: 98,
    SOC: 30,
    VIS: 25,
    HEA: 20,
    TOU: 27,
    BOD: 27,
    BAL: 25,
    PLA: 24,
    TOT: [122, 128],
  },
  {
    tScore: 70,
    percentile: 98,
    SOC: 29,
    VIS: 24,
    HEA: 19,
    TOU: [25, 26],
    BOD: [25, 26],
    BAL: 24,
    PLA: 25,
    TOT: [119, 121],
  },
  {
    tScore: 69,
    percentile: 97,
    SOC: 28,
    VIS: [21, 23],
    HEA: [17, 18],
    TOU: null,
    BOD: 24,
    BAL: 23,
    PLA: [21, 22],
    TOT: [110, 118],
  },
  {
    tScore: 68,
    percentile: 96,
    SOC: null,
    VIS: 20,
    HEA: 16,
    TOU: [23, 24],
    BOD: 23,
    BAL: [21, 22],
    PLA: 20,
    TOT: [106, 109],
  },
  {
    tScore: 67,
    percentile: 96,
    SOC: 27,
    VIS: 19,
    HEA: 15,
    TOU: 22,
    BOD: 22,
    BAL: 20,
    PLA: 19,
    TOT: [103, 105],
  },
  {
    tScore: 66,
    percentile: 95,
    SOC: 26,
    VIS: 18,
    HEA: 14,
    TOU: 21,
    BOD: 21,
    BAL: 19,
    PLA: 18,
    TOT: [99, 102],
  },
  {
    tScore: 65,
    percentile: 93,
    SOC: 25,
    VIS: 17,
    HEA: 13,
    TOU: 20,
    BOD: 20,
    BAL: 18,
    PLA: 17,
    TOT: [94, 98],
  },
  {
    tScore: 64,
    percentile: 92,
    SOC: 24,
    VIS: [15, 16],
    HEA: 12,
    TOU: 19,
    BOD: 19,
    BAL: 17,
    PLA: null,
    TOT: [92, 93],
  },
  {
    tScore: 63,
    percentile: 90,
    SOC: 23,
    VIS: 14,
    HEA: 11,
    TOU: 18,
    BOD: 18,
    BAL: [15, 16],
    PLA: 16,
    TOT: [88, 91],
  },
  {
    tScore: 62,
    percentile: 88,
    SOC: 22,
    VIS: null,
    HEA: null,
    TOU: 17,
    BOD: 17,
    BAL: null,
    PLA: 15,
    TOT: [84, 87],
  },
  {
    tScore: 61,
    percentile: 86,
    SOC: null,
    VIS: null,
    HEA: null,
    TOU: 16,
    BOD: 16,
    BAL: null,
    PLA: 14,
    TOT: [81, 83],
  },
  {
    tScore: 60,
    percentile: 84,
    SOC: 21,
    VIS: 13,
    HEA: 10,
    TOU: 15,
    BOD: 15,
    BAL: 14,
    PLA: 13,
    TOT: [79, 80],
  },
  {
    tScore: 59,
    percentile: 82,
    SOC: null,
    VIS: null,
    HEA: null,
    TOU: 14,
    BOD: 14,
    BAL: null,
    PLA: 12,
    TOT: [77, 78],
  },
  {
    tScore: 58,
    percentile: 79,
    SOC: 20,
    VIS: 12,
    HEA: 9,
    TOU: 13,
    BOD: 13,
    BAL: 13,
    PLA: 11,
    TOT: [75, 76],
  },
  {
    tScore: 57,
    percentile: 76,
    SOC: 19,
    VIS: 11,
    HEA: 8,
    TOU: 12,
    BOD: 12,
    BAL: 12,
    PLA: 10,
    TOT: [73, 74],
  },
  {
    tScore: 56,
    percentile: 73,
    SOC: 18,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: 11,
    BAL: 11,
    PLA: null,
    TOT: [71, 72],
  },
  {
    tScore: 55,
    percentile: 69,
    SOC: 17,
    VIS: null,
    HEA: null,
    TOU: 11,
    BOD: null,
    BAL: null,
    PLA: 9,
    TOT: 70,
  },
  {
    tScore: 54,
    percentile: 66,
    SOC: null,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: 10,
    BAL: 10,
    PLA: null,
    TOT: 69,
  },
  {
    tScore: 53,
    percentile: 62,
    SOC: 16,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: [67, 68],
  },
  {
    tScore: 52,
    percentile: 58,
    SOC: null,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: 66,
  },
  {
    tScore: 51,
    percentile: 54,
    SOC: 15,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: 65,
  },
  {
    tScore: 50,
    percentile: 50,
    SOC: null,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: 64,
  },
  {
    tScore: 49,
    percentile: 46,
    SOC: 14,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: 63,
  },
  {
    tScore: 48,
    percentile: 42,
    SOC: null,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: 62,
  },
  {
    tScore: 47,
    percentile: 38,
    SOC: 13,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: 61,
  },
  {
    tScore: 46,
    percentile: 34,
    SOC: null,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: 60,
  },
  {
    tScore: 45,
    percentile: 31,
    SOC: 12,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: 59,
  },
  {
    tScore: 44,
    percentile: 27,
    SOC: null,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: null,
  },
  {
    tScore: 43,
    percentile: 24,
    SOC: [10, 11],
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: null,
  },
  {
    tScore: 42,
    percentile: 21,
    SOC: null,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: null,
  },
  {
    tScore: 41,
    percentile: 18,
    SOC: null,
    VIS: null,
    HEA: null,
    TOU: null,
    BOD: null,
    BAL: null,
    PLA: null,
    TOT: null,
  },
  {
    tScore: 40,
    percentile: 16,
    SOC: null,
    VIS: 11,
    HEA: null,
    TOU: 10,
    BOD: 11,
    BAL: 9,
    PLA: null,
    TOT: [56, 58],
  },
];

const CODES: SpmNormedScaleCode[] = [
  "SOC",
  "VIS",
  "HEA",
  "TOU",
  "BOD",
  "BAL",
  "PLA",
  "TOT",
];

function expandCell(
  cell: Cell,
  entry: SpmNormEntry,
  map: Map<number, SpmNormEntry>,
) {
  if (cell == null) return;
  if (typeof cell === "number") {
    map.set(cell, entry);
    return;
  }
  const [min, max] = cell;
  for (let raw = min; raw <= max; raw += 1) {
    map.set(raw, entry);
  }
}

function buildTable(): SpmNormsTable {
  const maps = Object.fromEntries(
    CODES.map((code) => [code, new Map<number, SpmNormEntry>()]),
  ) as Record<SpmNormedScaleCode, Map<number, SpmNormEntry>>;

  // Linhas de T alto → baixo: primeira atribuição ganha (faixas altas prevalecem).
  for (const row of ROWS) {
    const entry: SpmNormEntry = {
      tScore: row.tScore,
      percentile: row.percentile,
    };
    for (const code of CODES) {
      expandCell(row[code], entry, maps[code]);
    }
  }

  return maps;
}

export const SPM_CASA_5ANOS_NORMS: SpmNormsTable = buildTable();

/** Exemplo do PDF (validação). */
export const SPM_CASA_5ANOS_GOLDEN = {
  raw: {
    SOC: 20,
    VIS: 31,
    HEA: 22,
    TOU: 24,
    BOD: 19,
    BAL: 22,
    PLA: 25,
    TOT: 128,
  },
  tScore: {
    SOC: 58,
    VIS: 77,
    HEA: 74,
    TOU: 68,
    BOD: 64,
    BAL: 68,
    PLA: 70,
    TOT: 71,
  },
} as const;
