autoInstallPeers: false
strictPeerDependencies: false
allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
overrides:
  better-sqlite3: "-"
  mysql2: "-"
