-- Align anamnese JSON field keys + roteiro categoryTicks to English

-- Anamnese data keys
UPDATE "anamneses" SET "data" = REPLACE("data", '"profissionaisAcompanham"', '"accompanyingProfessionals"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"profissionaisAcompanham::"', '"accompanyingProfessionals::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"gestacaoIntercorrencias"', '"pregnancyComplications"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"gestacaoIntercorrencias::"', '"pregnancyComplications::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"pesoIdadeGestacional"', '"birthWeightGestationalAge"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"pesoIdadeGestacional::"', '"birthWeightGestationalAge::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"avaliacoesComplementares"', '"complementaryAssessments"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"avaliacoesComplementares::"', '"complementaryAssessments::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"toleraMudancaBrincadeira"', '"toleratesPlayChange"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"toleraMudancaBrincadeira::"', '"toleratesPlayChange::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"ecolaliaOutrosPadroes"', '"echolaliaOtherPatterns"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"ecolaliaOutrosPadroes::"', '"echolaliaOtherPatterns::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"expressaNecessidades"', '"expressesNeeds"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"expressaNecessidades::"', '"expressesNeeds::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"seletividadeAlimentar"', '"foodSelectivity"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"seletividadeAlimentar::"', '"foodSelectivity::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"relacionamentoEscolar"', '"schoolRelationships"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"relacionamentoEscolar::"', '"schoolRelationships::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"adaptacoesEscolares"', '"schoolAdaptations"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"adaptacoesEscolares::"', '"schoolAdaptations::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"desempenhoEscolar"', '"schoolPerformance"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"desempenhoEscolar::"', '"schoolPerformance::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"terapiasAnteriores"', '"previousTherapies"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"terapiasAnteriores::"', '"previousTherapies::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"cirurgiasInternacoes"', '"surgeriesHospitalizations"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"cirurgiasInternacoes::"', '"surgeriesHospitalizations::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"alergiasConvulsoes"', '"allergiesSeizures"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"alergiasConvulsoes::"', '"allergiesSeizures::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"diagnosticosMedicos"', '"medicalDiagnoses"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"diagnosticosMedicos::"', '"medicalDiagnoses::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"medicamentosAtuais"', '"currentMedications"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"medicamentosAtuais::"', '"currentMedications::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"frequenciaSugerida"', '"suggestedFrequency"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"frequenciaSugerida::"', '"suggestedFrequency::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"obsFamiliaImportante"', '"importantFamilyNotes"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"obsFamiliaImportante::"', '"importantFamilyNotes::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"sensorialSistemas"', '"sensorySystems"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"sensorialSistemas::"', '"sensorySystems::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"brincarPredominante"', '"predominantPlay"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"brincarPredominante::"', '"predominantPlay::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"interacaoColegas"', '"peerInteraction"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"interacaoColegas::"', '"peerInteraction::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"sensOlfativoOral"', '"sensOlfactoryOral"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"sensOlfativoOral::"', '"sensOlfactoryOral::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"sensProprioceptivo"', '"sensProprioceptive"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"sensProprioceptivo::"', '"sensProprioceptive::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"funcoesExecutivas"', '"executiveFunctions"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"funcoesExecutivas::"', '"executiveFunctions::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"historicoFamiliar"', '"familyHistory"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"historicoFamiliar::"', '"familyHistory::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"objetivosIniciais"', '"initialGoals"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"objetivosIniciais::"', '"initialGoals::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"areasImpactadas"', '"impactedAreas"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"areasImpactadas::"', '"impactedAreas::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"contatoEmergencia"', '"emergencyContact"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"contatoEmergencia::"', '"emergencyContact::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"queixaDificuldades"', '"chiefComplaintDifficulties"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"queixaDificuldades::"', '"chiefComplaintDifficulties::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"queixaMotivou"', '"chiefComplaintReason"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"queixaMotivou::"', '"chiefComplaintReason::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"queixaDesejo"', '"chiefComplaintDesire"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"queixaDesejo::"', '"chiefComplaintDesire::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"objetivos6meses"', '"goals6Months"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"objetivos6meses::"', '"goals6Months::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"marcosLinguagem"', '"languageMilestones"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"marcosLinguagem::"', '"languageMilestones::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"marcosMotores"', '"motorMilestones"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"marcosMotores::"', '"motorMilestones::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"alimentacaoRotina"', '"feedingRoutine"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"alimentacaoRotina::"', '"feedingRoutine::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"cortesUnhaCabelo"', '"nailHairCutting"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"cortesUnhaCabelo::"', '"nailHairCutting::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"tarefasDomesticas"', '"householdTasks"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"tarefasDomesticas::"', '"householdTasks::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"desencadeiaCrises"', '"crisisTriggers"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"desencadeiaCrises::"', '"crisisTriggers::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"rigidezMudancas"', '"rigidityChanges"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"rigidezMudancas::"', '"rigidityChanges::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"hipDiscriminacao"', '"hypDiscrimination"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"hipDiscriminacao::"', '"hypDiscrimination::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"hipCoordenacao"', '"hypCoordination"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"hipCoordenacao::"', '"hypCoordination::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"visaoAudicao"', '"visionHearing"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"visaoAudicao::"', '"visionHearing::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"utiNeonatal"', '"neonatalIcu"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"utiNeonatal::"', '"neonatalIcu::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"obsDesfralde"', '"toiletTrainingNotes"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"obsDesfralde::"', '"toiletTrainingNotes::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"mobilidadeCasa"', '"homeMobility"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"mobilidadeCasa::"', '"homeMobility::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"nocaoPerigo"', '"dangerAwareness"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"nocaoPerigo::"', '"dangerAwareness::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"autonomiaGeral"', '"generalAutonomy"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"autonomiaGeral::"', '"generalAutonomy::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"comoComunica"', '"howCommunicates"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"comoComunica::"', '"howCommunicates::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"ajudaAcalmar"', '"calmingHelps"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"ajudaAcalmar::"', '"calmingHelps::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"hipModulacao"', '"hypModulation"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"hipModulacao::"', '"hypModulation::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"hipRegulacao"', '"hypRegulation"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"hipRegulacao::"', '"hypRegulation::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"recursosFortes"', '"strengths"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"recursosFortes::"', '"strengths::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"obsSensorial"', '"sensoryNotes"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"obsSensorial::"', '"sensoryNotes::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"nomeCrianca"', '"childName"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"nomeCrianca::"', '"childName::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"dataNascimento"', '"birthDate"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"dataNascimento::"', '"birthDate::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"diagnosticos"', '"diagnoses"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"diagnosticos::"', '"diagnoses::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"avdAlimentacao"', '"adlFeeding"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"avdAlimentacao::"', '"adlFeeding::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"avdHigiene"', '"adlHygiene"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"avdHigiene::"', '"adlHygiene::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"avdVestuario"', '"adlDressing"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"avdVestuario::"', '"adlDressing::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"avdBanheiro"', '"adlToileting"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"avdBanheiro::"', '"adlToileting::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"sensTatil"', '"sensTactile"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"sensTatil::"', '"sensTactile::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"sensAuditivo"', '"sensAuditory"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"sensAuditivo::"', '"sensAuditory::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"horarioSono"', '"sleepSchedule"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"horarioSono::"', '"sleepSchedule::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"diaTipico"', '"typicalDay"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"diaTipico::"', '"typicalDay::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"usoTelas"', '"screenUse"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"usoTelas::"', '"screenUse::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"compreensao"', '"comprehension"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"compreensao::"', '"comprehension::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"possuiIrmaos"', '"hasSiblings"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"possuiIrmaos::"', '"hasSiblings::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"quemMora"', '"householdMembers"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"quemMora::"', '"householdMembers::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"tipoParto"', '"deliveryType"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"tipoParto::"', '"deliveryType::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"prioridades"', '"priorities"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"prioridades::"', '"priorities::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"parentesco"', '"relationship"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"parentesco::"', '"relationship::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"responsavel"', '"guardianName"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"responsavel::"', '"guardianName::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"serieAno"', '"gradeYear"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"serieAno::"', '"gradeYear::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"telefone"', '"phone"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"telefone::"', '"phone::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"escola"', '"school"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"escola::"', '"school::"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"idade"', '"age"');
UPDATE "anamneses" SET "data" = REPLACE("data", '"idade::"', '"age::"');

-- Roteiro category ticks
UPDATE "roteiro_notes" SET "categoryTick" = 'bilateral-integration' WHERE "categoryTick" = 'INTEGR. BILATERAL';
UPDATE "roteiro_notes" SET "categoryTick" = 'motor-planning' WHERE "categoryTick" = 'PLANEJ. MOTOR';
UPDATE "roteiro_notes" SET "categoryTick" = 'proprioceptive' WHERE "categoryTick" = 'PROPRIOCEPTIVO';
UPDATE "roteiro_notes" SET "categoryTick" = 'mealtime-behavior' WHERE "categoryTick" = 'COMPORTAMENTO';
UPDATE "roteiro_notes" SET "categoryTick" = 'oral-motor' WHERE "categoryTick" = 'ORAL-MOTOR';
UPDATE "roteiro_notes" SET "categoryTick" = 'vestibular' WHERE "categoryTick" = 'VESTIBULAR';
UPDATE "roteiro_notes" SET "categoryTick" = 'modulation' WHERE "categoryTick" = 'MODULAÇÃO';
UPDATE "roteiro_notes" SET "categoryTick" = 'grasp' WHERE "categoryTick" = 'PREENSÃO';
UPDATE "roteiro_notes" SET "categoryTick" = 'fluency' WHERE "categoryTick" = 'FLUÊNCIA';
UPDATE "roteiro_notes" SET "categoryTick" = 'textures' WHERE "categoryTick" = 'TEXTURAS';
UPDATE "roteiro_notes" SET "categoryTick" = 'scissors' WHERE "categoryTick" = 'TESOURA';
UPDATE "roteiro_notes" SET "categoryTick" = 'food-groups' WHERE "categoryTick" = 'GRUPOS';
UPDATE "roteiro_notes" SET "categoryTick" = 'mealtime-routine' WHERE "categoryTick" = 'ROTINA';
UPDATE "roteiro_notes" SET "categoryTick" = 'letters' WHERE "categoryTick" = 'LETRAS';
UPDATE "roteiro_notes" SET "categoryTick" = 'spatial' WHERE "categoryTick" = 'ESPAÇO';
UPDATE "roteiro_notes" SET "categoryTick" = 'praxis' WHERE "categoryTick" = 'PRÁXIS';
UPDATE "roteiro_notes" SET "categoryTick" = 'tactile' WHERE "categoryTick" = 'TÁTIL';
UPDATE "roteiro_notes" SET "categoryTick" = 'visual' WHERE "categoryTick" = 'VISUAL';
UPDATE "roteiro_notes" SET "categoryTick" = 'stroke' WHERE "categoryTick" = 'TRAÇO';
